const images = {
  bg: require('../res/image/bg.png'),
  card: require('../res/image/card.png'),
  moon: require('../res/image/moon.png'),
  iconIt: require('../res/image/it.png'),
  iconInfo: require('../res/image/information.png'),
  iconBell: require('../res/image/bell.png'),
  iconBack: require('../res/image/arrow-left.png'),
  password: require('../res/image/password.png'),
  iconTeam: require('../res/image/team.png'),
  iconBooks: require('../res/image/books.png'),
  iconLogout: require('../res/image/logout.png'),
  iconSchool: require('../res/image/school.png'),
  iconSetting: require('../res/image/maintenance.png'),
  translation: require('../res/image/translation.png'),
  iconProject: require('../res/image/project.png'),
  iconTabMenu: require('../res/image/tabmenu.png'),
  iconExercise: require('../res/image/exercise.png'),
  iconMenuActive: require('../res/image/open-menu-1.png'),
  iconMenuInactive: require('../res/image/open-menu.png'),
  iconPersonActive: require('../res/image/person.png'),
  iconPersonProfile: require('../res/image/person-profile.png'),
  iconPersonInactive: require('../res/image/person-1.png'),
  iconTimetable: require('../res/image/calendar.png'),
  iconScoretable: require('../res/image/score.png'),
  iconElearning:require('../res/image/Elearning.png'),
  iconTTTH:require('../res/image/Flat.png'),
  iconTimer:require('../res/image/notification.png'),
  iconSeen:require('../res/image/seen.png'),
  cover1: require('../res/image/coverImg/cover(1).png'),
  cover2: require('../res/image/coverImg/cover(2).png'),
  cover3: require('../res/image/coverImg/cover(3).png'),
  cover4: require('../res/image/coverImg/cover(4).png'),
  cover5: require('../res/image/coverImg/cover(5).png'),
  cover6: require('../res/image/coverImg/cover(6).png'),
  cover7: require('../res/image/coverImg/cover(7).png'),
  cover8: require('../res/image/coverImg/cover(8).png'),
  cover9: require('../res/image/coverImg/cover(9).png'),
};
export default images;
