const images = {
  bg: require('../res/image/bg.png'),
  card: require('../res/image/card.png'),
  moon: require('../res/image/moon.png'),
  iconIt: require('../res/image/it.png'),
  iconInfo: require('../res/image/information.png'),
  iconBell: require('../res/image/bell.png'),
  iconBack: require('../res/image/arrow-left.png'),
  password: require('../res/image/password.png'),
  iconTeam: require('../res/image/team.png'),
  iconBooks: require('../res/image/books.png'),                       
  iconLogout: require('../res/image/logout.png'),
  iconSchool: require('../res/image/school.png'),                                                                
  iconSetting: require('../res/image/maintenance.png'),
  translation: require('../res/image/translation.png'),
  iconProject: require('../res/image/project.png'),
  icontabmenu:require('../res/image/tabmenu.png'),
  iconExercise: require('../res/image/exercise.png'),
  iconMenuActive: require('../res/image/open-menu-1.png'),
  iconMenuInactive: require('../res/image/open-menu.png'),
  iconPersonActive: require('../res/image/person.png'),
  iconPersonProfile: require('../res/image/person-profile.png'),
  iconPersonInactive: require('../res/image/person-1.png'),

};
export default images;
