export const FORMAT_DATA = 'FORMAT_DATA';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const GET_MENU_NEWS = 'GET_MENU_NEWS';
export const GET_MENU_NEWS_SUCCESS = 'GET_MENU_NEWS_SUCCESS';
export const GET_MENU_NEWS_FAIL = 'GET_MENU_NEWS_FAIL';

export const CHANGE_STATE_LOGIN = "CHANGE_STATE_LOGIN";

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';